### ISSUE TITLE
How to access static methods of DecoratedComponent?

### ISSUE THREAD

**Issue by jbroadice** [iam4x/connect-alt#1]
Hi again!

I've been playing around with using `react-router` `onEnter` hook to fetch async data from the next component/page if needed. I sort of had this working before by doing something like:

``` javascript
const { component } = nextState.routes[1];

if (typeof component.fetchData === 'function') {
   // ... trigger fetchData and then listen to requests store changes
}
```

I am not sure how to go about this as the component that `react-router` now provides is the `ConnectToStoresWrapper`. Any ideas?

**Comment by iam4x** [comment]
@jchapple What is the advantage of using a static method for fetching data? Why not using the `componentWillMount` with alt-resolver?

Anyway I'll update `connect-alt` for copying static methods of the decorated component :+1:

**Comment by jbroadice** [comment]
Because `componentWillMount` is not executed until after the `callback` is called from within `onEnter`, which is too late.

**Comment by jbroadice** [comment]
I am still, however, triggering Flux actions (rather than direct API calls) from within the `onEnter` method. So it is still using `alt-resolver` and the usual Flux async flow.

**Comment by iam4x** [comment]
@jchapple Oh, you are firing the transition when the store has changed? So the render isn't done before data is fetched on client side?

**Comment by jbroadice** [comment]
Yeah. Is that bad? :/

**Comment by iam4x** [comment]
No it's pretty smart! This fix your issue https://github.com/iam4x/isomorphic-flux-boilerplate/issues/127 ?

**Comment by iam4x** [comment]
@jchapple I have the fix in head, but I would like to right some tests so it's gonna take me some time.

Here's the gist: https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=class%20Foobar%20%7B%0A%20%20%0A%20%20static%20state%20%3D%20%7B%20foo%3A%20'bar'%20%7D%0A%20%20%0A%20%20foo%20%3D%20'bar'%0A%20%20%0A%20%20componentWillMount()%20%7B%0A%20%20%20%20console.log('lol')%3B%0A%20%20%7D%0A%20%20%0A%7D%0A%0Aconst%20staticMethods%20%3D%20Object.keys(Foobar)%3B%0Aconsole.log(staticMethods)%3B

**Comment by jbroadice** [comment]
Haha, cool! Yeah - more or less. There are some caveats to the approach - I'll post about it in the other thread.

Thanks for the fix. :+1:
