### ISSUE TITLE
Support multiple stores?

### ISSUE THREAD

**Issue by beckend** [iam4x/connect-alt#10]
I'm using your boilerplate, and I noticed I had to do:

@connect('session')
@connect('requests')
@connect('another')
Class...

Instead of @connect('session', 'requests', 'another')

**Comment by iam4x** [comment]
@beckend if you don't specify a store at first parameter, you will get all the stores in your reducer function parameters:

```
@connect(({ session, request, foobar }) => ({ session, request, foobar }))
class FooComponent { ... }
```

What you want to do is having:

```
@connect('foo', 'bar')
class FooComponent { ... }
```

and have `this.props.fooStore` and `this.props.barStore` into props?

**Comment by beckend** [comment]
Ok thanks for the suggestion, I ended up with

```
@connect(({ session, requests }) => {
  return {
    inProgress: requests.inProgress,
    session: (session.toJS()).session
  };
})

```

Converted session store to immutable,
