### ISSUE TITLE
Accessing DecoratedComponent[prop] causes TypeError in Safari in production

### ISSUE THREAD

**Issue by jbroadice** [iam4x/connect-alt#2]
[This line](https://github.com/iam4x/connect-alt/blob/71445d0a5f6bfce5212a1ea59ef03925d1dae798/src/main.js#L41) seems to be breaking things on Safari (Version 9.0 (11601.1.56)) and iOS Safari (latest), but only when running in production mode. No idea why. 

It seems that accessing `DecoratedComponent[prop]` will throw a `TypeError` for certain properties (e.g. there is one called 'arguments'). Adding a try/catch block round the if statement this seems to prevent the error...

The error completely stops the app from bootstrapping on the client.

![screen shot 2015-11-04 at 22 30 36](https://cloud.githubusercontent.com/assets/5153746/10954159/b5be6e38-8343-11e5-9004-d137defecee2.png)
![screen shot 2015-11-04 at 22 27 58](https://cloud.githubusercontent.com/assets/5153746/10954160/b5bec202-8343-11e5-9873-a5ec18d83c58.png)

**Comment by iam4x** [comment]
Does last release solves the problem for you?

**Comment by jbroadice** [comment]
Thanks a lot. Works a treat. :sparkles:
