### ISSUE TITLE
Custom `takeSnapshot` does not serialize store data

### ISSUE THREAD

**Issue by jbroadice** [iam4x/connect-alt#3]
Me again! Just a quick one... :stuck_out_tongue: 

Before, when you were using `flux.takeSnapshot()`, the store's data was being serialized, which was useful when, for example, using alt's [immutable store decorator](https://github.com/altjs/utils/blob/master/src/ImmutableUtil.js).

Is it possible to have the new `takeSnapshot` serialize the store's data, also?

**Comment by iam4x** [comment]
@jchapple Hmmmm, you are right. I tried to avoid `onSerialize` calls because of an issue on IE8, see https://github.com/goatslacker/alt/issues/535

I'll revert my update.

**Comment by jbroadice** [comment]
Thank you.

**Comment by jbroadice** [comment]
Hey. Just a quick note that I've decided it's better to not have the state serialized when using Immutable stores, because you can't get those cheap comparisons (`===`) in `shouldComponentUpdate` unless you're referencing the un-copied objects.

**Comment by jbroadice** [comment]
Perhaps reverting to the earlier custom [takeSnapshot](https://github.com/iam4x/connect-alt/blob/ee95321f85d0e5ad68afa17ec0bbf54120407c01/src/main.js#L24) might solve the problem [here](https://github.com/iam4x/connect-alt/pull/5)?

**Comment by iam4x** [comment]
@jchapple What is the behaviour when you call `store.getState()` I want to have the same behaviour. I don't think the data is serialized, so yeah we could go back to the custom `takeSnaphot` :+1:

**Comment by jbroadice** [comment]
The data isn't serialized when using `getState()`

**Comment by iam4x** [comment]
Let's rollback to the custom method, it will closes #5 also.
